APP_VERSION = "1.0.0"
APP_NAME = "StemSplitAI"
APP_PUBLISHER = "Akifs52"
APP_URL = "https://github.com/akifs52/StemSplitterai"
GITHUB_RELEASES_URL = "https://github.com/akifs52/StemSplitterai/releases"
LATEST_JSON_URL = "https://raw.githubusercontent.com/akifs52/StemSplitterai/main/latest.json"
