audio:
  chunk_size: 176128
  dim_f: 1024
  dim_t: 344
  hop_length: 512
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  dim: 128
  depth: 3
  stereo: true
  num_stems: 2
  time_transformer_depth: 1
  freq_transformer_depth: 1
  linear_transformer_depth: 0
  num_bands: 48
  dim_head: 64
  heads: 6
  attn_dropout: 0.1
  ff_dropout: 0.1
  flash_attn: True
  dim_freqs_in: 1025
  sample_rate: 44100
  stft_n_fft: 2048
  stft_hop_length: 512
  stft_win_length: 2048
  stft_normalized: False
  mask_estimator_depth: 2
  multi_stft_resolution_loss_weight: 1.0
  multi_stft_resolutions_window_sizes: !!python/tuple
    - 4096
    - 2048
    - 1024
    - 512
    - 256
  multi_stft_hop_size: 147
  multi_stft_normalized: False
  mlp_expansion_factor: 4
  use_torch_checkpoint: True
  skip_connection: True

training:
  batch_size: 2
  gradient_accumulation_steps: 2
  grad_clip: 1.0
  instruments:
    - lead_guitar
    - rhythm_guitar
  lr: 2.0e-04
  patience: 20
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 200
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: false
  ema_momentum: 0.999
  optimizer: adamw
  weight_decay: 0.01
  scheduler: cosine
  num_warmup_steps: 1000
  other_fix: false
  use_amp: true

loss:
  l1_waveform: true
  l1_waveform_coef: 1.0
  multi_stft: true
  multi_stft_coef: 1.0
  spectral_convergence: true
  spectral_convergence_coef: 0.5
  si_sdr: false
  si_sdr_coef: 0.0
  stem_leakage: false
  stem_leakage_coef: 0.0
  stereo_consistency: false
  stereo_consistency_coef: 0.0
  center_aware_lead: false
  center_aware_lead_coef: 0.0
  min_energy: true
  min_energy_coef: 2.0
  min_energy_threshold: 0.01

augmentations:
  enable: true
  loudness: true
  loudness_min: 0.8
  loudness_max: 1.2
  eq: true
  saturation: true
  saturation_drive_min: 0.0
  saturation_drive_max: 0.2
  panning: true
  panning_min: 0.8
  panning_max: 1.0
  time_mask: true
  time_mask_max_sec: 0.2
  freq_mask: true
  freq_mask_max_bands: 2

inference:
  batch_size: 1
  dim_t: 344
  num_overlap: 4
