audio:
  chunk_size: 264600
  dim_f: 1024
  dim_t: 517
  hop_length: 512
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  dim: 192
  depth: 5
  stereo: true
  num_stems: 2
  time_transformer_depth: 1
  freq_transformer_depth: 1
  linear_transformer_depth: 0
  num_bands: 60
  dim_head: 64
  heads: 6
  attn_dropout: 0.05
  ff_dropout: 0.05
  flash_attn: True
  dim_freqs_in: 1025
  sample_rate: 44100
  stft_n_fft: 2048
  stft_hop_length: 512
  stft_win_length: 2048
  stft_normalized: False
  mask_estimator_depth: 3
  multi_stft_resolution_loss_weight: 1.0
  multi_stft_resolutions_window_sizes: !!python/tuple
    - 4096
    - 2048
    - 1024
    - 512
    - 256
  multi_stft_hop_size: 147
  multi_stft_normalized: False
  mlp_expansion_factor: 4
  use_torch_checkpoint: True
  skip_connection: True
  match_input_audio_length: True

training:
  batch_size: 1
  gradient_accumulation_steps: 8
  grad_clip: 0.5
  instruments:
    - lead_guitar
    - rhythm_guitar
  lr: 4.0e-05
  patience: 20
  reduce_factor: 0.9
  target_instrument: null
  num_epochs: 300
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: false
  ema_momentum: 0.0
  optimizer: adamw
  weight_decay: 0.01
  scheduler: cosine
  num_warmup_steps: 1000
  other_fix: false
  use_amp: true

loss:
  l1_waveform: true
  l1_waveform_coef: 1.0
  multi_stft: true
  multi_stft_coef: 1.0
  spectral_convergence: true
  spectral_convergence_coef: 0.5
  min_energy: true
  min_energy_coef: 4.0
  min_energy_threshold: 0.10
  min_target_energy: 1.0e-07
  si_sdr: true
  si_sdr_coef: 0.05
  si_sdr_max_db: 20.0
  mixture_consistency: true
  mixture_consistency_coef: 0.75
  mixture_consistency_stft_weight: 0.25
  spectral_overlap: true
  spectral_overlap_coef: 0.35
  spectral_overlap_n_fft: 2048
  spectral_overlap_hop_length: 512
  spectral_overlap_power: 1.0

augmentations:
  enable: true
  loudness: true
  loudness_min: 0.8
  loudness_max: 1.2
  eq: false
  saturation: false
  panning: true
  panning_min: 0.85
  panning_max: 1.0
  time_mask: true
  time_mask_max_sec: 0.15
  freq_mask: true
  freq_mask_max_bands: 2

inference:
  batch_size: 1
  dim_t: 517
  num_overlap: 4
